/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123837-g235d5fd30a-20260405"
#endif /* AVUTIL_FFVERSION_H */
